### ISSUE TITLE
ECOGEN unknown error

### ISSUE THREAD

**Issue by jr144393** [code-mphi/ECOGEN#40] opened 2023-08-22 16:17 UTC
The issue that I am encountering is an error output that I cannot back trace - 

terminate called after throwing an instance of 'std::length_error'
  what():  vector::_M_default_append

The error occurs upon call to 3D simulations, with or without MPI

I expected that there would be a timestep zero but the error is not one I am familiar with, could someone please assist?

**Comment by kevinschmidmayer** [comment] 2023-08-22 19:59
Hi @jr144393,

Sorry but I don't understand your error. Could you please fully detailed your situation (test case, complete terminal output, ...)?

Best regards,
Kevin

**Comment by jr144393** [comment] 2023-08-22 20:22
The case follows the same logic as the helium bubble case, but is using a water droplet. I have run this case elsewhere just not in 3D. The complete terminal output is:


************************************************************

    ,---.     ,--,    .---.     ,--,    ,---.    .-. .-.
    | .-'   .' .')   / .-. )  .' .'     | .-'    |  \| |
    | `-.   |  |(_)  | | |(_) |  |  __  | `-.    |   | |
    | .-'   \  \     | | | |  \  \ ( _) | .-'    | |\  |
    |  `--.  \  `-.  \ `-' /   \  `-) ) |  `--.  | | |)|
    /( __.'   \____\  )---'    )\____/  /( __.'  /(  (_)
   (__)              (_)      (__)     (__)     (__)
   Official webSite: https://code-mphi.github.io/ECOGEN/

************************************************************
           EXECUTION OF THE TEST CASE NUMBER: 1
************************************************************
T1 | Test case: ./ecogen_amr_deck/
terminate called after throwing an instance of 'std::length_error'
  what():  vector::_M_default_append
 *** Process received signal ***
 Signal: Aborted (6)
 Signal code:  (-6)
 [ 0] /lib64/libpthread.so.0(+0x12cf0)[0x150d88968cf0]
 [ 1] /lib64/libc.so.6(gsignal+0x10f)[0x150d885deaff]
 [ 2] /lib64/libc.so.6(abort+0x127)[0x150d885b1ea5]
 [ 3] /lib64/libstdc++.so.6(+0x9009b)[0x150d891a009b]
 [ 4] /lib64/libstdc++.so.6(+0x9653c)[0x150d891a653c]
 [ 5] /lib64/libstdc++.so.6(+0x96597)[0x150d891a6597]
 [ 6] ./ECOGEN[0x40cb4b]
*** End of error message ***
Aborted (core dumped)

**Comment by kevinschmidmayer** [comment] 2023-08-23 08:16
I'm sorry but I have no idea what it could be. I can only advise to carefully verify the input files if they all makes sense for 3D computations. If they do, you will have to use prints in the code or debug mode to figure out where the problem is coming from. We never had such issues and with this little information, it's impossible for us to guess.
You could also simplify your problem to come back to something that works and progressively change your setup to figure out at which exact step the problem appears.

Please keep us informed.

**Comment by jr144393** [comment] 2023-08-24 15:04
No worries, I am wondering if it is an encoding issue since I brought the files over from windows to linux. In the past I have had unknown errors in python scripts due to something like an incorrect end of line character. I will try a few things including working it back to a working example first.

**Comment by kevinschmidmayer** [comment] 2023-09-15 07:57
Hello @jr144393,

Did you solve your issue?

Best regards,
Kevin

**Comment by jr144393** [comment] 2023-09-15 12:57
Kevin,

It seemed to be an incorrect reference to the transport color equations. (Essentially it was not being referenced properly). I am not sure why this particular error is appearing, but as I started retyping the files from scratch I had also noticed the transport variable issue. 

I am okay with having this issue closed - thank you for checking back in.

Jeremy

**Comment by kevinschmidmayer** [comment] 2023-09-15 19:49
Alright. Don't know what happened but if this is good for you now. As you said, I'll close the issue. Thank you for your quick response.

**Closed as completed by kevinschmidmayer** 2023-09-15 19:49 UTC
